apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: rahmafeidi/node-app
        ports:
        - containerPort: 3005
       
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodeapp
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 3005
    nodePort: 30000
  selector:
    app: nodeapp
